### ISSUE TITLE
Pretrained Checkpoints

### ISSUE THREAD

**Issue by joshinh** [SawanKumar28/nile#2]
Firstly, thanks for releasing the code! I was wondering if you are planning to release pre-trained checkpoints for the best models (both the fine-tuned LM used to generate explanations and the classifier model)

**Comment by SawanKumar28** [comment]
Thanks for your interest in the work. The pre-trained model details can now be found in the [README](https://github.com/SawanKumar28/nile/blob/master/README.md) under "Pre-trained models".
