### ISSUE TITLE
MNLI download permission issue

### ISSUE THREAD

**Issue by shanestorks** [SawanKumar28/nile#5]
When trying to fetch the data using fetch_data.sh, I run into an error `urllib.error.HTTPError: HTTP Error 403: Forbidden`. Is the download link broken?

**Comment by SawanKumar28** [comment]
It looks like the older link is broken. I have updated the script with a new link and it should work now.
In any case, MNLI download was what was failing and you can comment that line out if you don't need it.

**Comment by shanestorks** [comment]
Thank you!
